baseURL = 'https://michaeldoan.com/'
languageCode = 'en-us'
title = 'Michael Doan'
theme = 'Typo'

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

breadcrumbs = true

[params]
# homeIntroTitle = "Hello!"
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

homeIntroContent = """
I'm a certified public accountant and co-founder of [Basis 365 Accounting](https://www.basis365.com). 
"""
# This website is a collection of my [writing](/posts).

[[params.social]]
name = "X"
url = "https://x.com/michaeltdoan"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/michaeldoan/"

listDateFormat = 'Jan 2,  2006'

showFooter = true
footerContent = "2025"