baseURL = 'https://michaeldoan.com/'
languageCode = 'en-us'
title = 'Michael Doan'
theme = 'Typo'
publishDir = "."

[params]
# homeIntroTitle = "Hello!"
homeCollectionTitle = 'Writing'
homeCollection = 'writing'
showFooter = true
footerContent = "2025"
homeIntroContent = """
I'm a certified public accountant and co-founder of [Basis 365 Accounting](https://www.basis365.com).

Before launching Basis 365, I spent years as an audit partner at a CPA firm, where I worked closely with public and private companies, guiding them through audits and SEC filings. My journey has also included roles as a controller and vice president of finance for several corporations, giving me a well-rounded perspective on accounting and financial leadership.

This website is where I share my thoughts, ideas, and expertise. You can find me on [X](https://x.com/michaeltdoanh) and [LinkedIn](https://www.linkedin.com/in/michaeldoan/).
"""
# Breadcrumbs
breadcrumbs = false

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = 'Jan 2, 2006'

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "writing"
url = "/writing"

# [params] I don't use

# [[params.social]]
# name = "X"
# url = "https://x.com/michaeltdoan"

# [[params.social]]
# name = "LinkedIn"
# url = "https://www.linkedin.com/in/michaeldoan/"